sudo: enabled
dist: xenial
language: python

python:
 - '2.7'

install:
 - pip install -r requirements-dev.txt

script:
  - flake8 pytest_hercule --max-line-length=100

after_success:
 - codecov -t "$CODECOV_TOKEN"

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJGMwY2E5MGRmLTkwYTItNGM1Zi04MGM1LWY0YjE4Y2M0NmI1YwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYghj-nM8DhlSfxGkzexizYk06N-j7iD_2-VW3yijapWG8
  on:
    tags: true
    all_branches: true
    python: 2.7