sudo: enabled
dist: xenial
language: python

python:
  - '2.7'
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install -r requirements-dev.txt

script:
  - flake8 pytest_sherlock --max-line-length=100
  - pytest -vv --cov-report xml --cov=pytest_sherlock tests/pytest_sherlock

after_success:
 - bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN"

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: "__token__"
  password:
    secure: "$PYPI_TOKEN"
  on:
    tags: true
    all_branches: true
    python: 2.7