sudo: enabled
dist: xenial
language: python
python:
- '2.7'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements-dev.txt
script:
- flake8 pytest_sherlock --max-line-length=100
- pytest tests/ --ignore="tests/exmaple" -vv --cov-report xml --cov=pytest_sherlock
after_success:
- bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password: pypi-AgEIcHlwaS5vcmcCJGE1Yjc4NGE4LWQ1MzMtNGFmYS05Y2NhLTA1OTQ1NzRhMzFlYwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgGNRu-XeJuBKhu917ld1pIuoYXBRNt30kgCYHxpQFA6I
  on:
    tags: true
    python: 2.7
