sudo: enabled
dist: xenial
language: python

python:
  - '2.7'

install:
  - pip install -r requirements-dev.txt

script:
  - flake8 pytest_sherlock --max-line-length=100
  - pytest -vv tests/pytest_sherlock

after_success:
 - codecov -t "$CODECOV_TOKEN"

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: "__token__"
  password:
    secure: "$PYPI_TOKEN"
  on:
    tags: true
    all_branches: true
    python: 2.7